### ISSUE TITLE
全屏状态下无法显示弹幕&prior为false,在发送模式下还是会被强制改成true

### ISSUE THREAD

**Issue by PMBRK** [feiafei27/fly-barrage#1]
问题1：全屏状态下无法显示弹幕
<img width="638" alt="image" src="https://github.com/feiafei27/fly-barrage/assets/16216561/f9090005-55fb-4b01-9bf4-d96bdfcda01a">
<img width="823" alt="image" src="https://github.com/feiafei27/fly-barrage/assets/16216561/5923b06c-6cbf-4120-acd8-396145c79571">

问题2：prior为false,在发送模式下还是会被强制改成true（或许某些场景下，并不一定要把发送和接受的消息区分开）
建议：发送边框提供圆角，边距。（边框和文本挤在一起并不好看）

**Comment by feiafei27** [comment]
问题一：还没想好怎么处理，稍后研究下；
问题二：的确这样设计比较好，弹幕是否渲染边框应该是上层应用决定的，框架不应该写死；边框的样式我稍后会新增一个自定义接口，用户可以自定义渲染边框；

**Comment by feiafei27** [comment]
v2.2.0 已上线；
1：新发送弹幕的 prior 属性不会被强制设置为 true，该属性应该由上层应用控制；
2：renderConfig 中增加了 priorBorderCustomRender 配置，用户可自定义 prior 弹幕的边框，完整 DEMO 中已实现，可参考；
